lsi: false
safe: true
source: /
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
remote_theme: knowledgepixels/pages-theme
plugins:
- jekyll-remote-theme
title: "global representations for all kinds of collaborative units"
logo: logo.svg
description: ""
footer: ""
